CREATE TABLE `ADD_INFO` (
	`ADD_INFO_ID`	VARCHAR(50)	NOT NULL,
	`DEL_ADD`	VARCHAR(255)	NULL,
	`HOBBY`	VARCHAR(255)	NULL
);

CREATE TABLE `USERS_ADD_INFO` (
	`USERS_ADD_INFO`	VARCHAR(50)	NOT NULL,
	`USERS_ID`	VARCHAR(50)	NOT NULL,
	`ADD_INFO_ID`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `USERS` (
	`USERS_ID`	VARCHAR(50)	NOT NULL,
	`NAME`	VARCHAR(255)	NULL,
	`AGE`	INTEGER(20)	NULL,
	`GENDER`	CHAR(10)	NULL,
	`PHONE`	VARCHAR(255)	NULL,
	`EMAIL`	VARCHAR(255)	NULL
);

ALTER TABLE `ADD_INFO` ADD CONSTRAINT `PK_ADD_INFO` PRIMARY KEY (
	`ADD_INFO_ID`
);

ALTER TABLE `USERS_ADD_INFO` ADD CONSTRAINT `PK_USERS_ADD_INFO` PRIMARY KEY (
	`USERS_ADD_INFO`,
	`USERS_ID`,
	`ADD_INFO_ID`
);

ALTER TABLE `USERS` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`USERS_ID`
);

ALTER TABLE `USERS_ADD_INFO` ADD CONSTRAINT `FK_USERS_TO_USERS_ADD_INFO_1` FOREIGN KEY (
	`USERS_ID`
)
REFERENCES `USERS` (
	`USERS_ID`
);

ALTER TABLE `USERS_ADD_INFO` ADD CONSTRAINT `FK_ADD_INFO_TO_USERS_ADD_INFO_1` FOREIGN KEY (
	`ADD_INFO_ID`
)
REFERENCES `ADD_INFO` (
	`ADD_INFO_ID`
);

